version: '3'

services:
  mariadb:
    healthcheck:
      test: ["CMD", "mysql", "--version"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 2s
    image: mariadb:latest
    container_name: slurm_mariadb
    networks:
      - slurm-network
    volumes:
      - ./mariadb_docker/database:/var/lib/mysql
    environment:
      - MARIADB_USER=slurm-user
      - MARIADB_PASSWORD=slurm
      - MARIADB_ROOT_PASSWORD=suslurm
    logging:
        driver: none

  slurm_dbd:
    depends_on:
      mariadb:
        condition: service_healthy
    image: slurm_db_daemon
    container_name: slurm_db
    networks:
      - slurm-network
    volumes:
      - ./slurm_conf:/etc/slurm
    hostname: slurm_db
    logging:
        driver: none

  slurm_head:
    depends_on:
      slurm_dbd:
        condition: service_started
    image: slurm_head
    container_name: slurm_head
    networks:
      - slurm-network
    volumes:
      - ./slurm_conf:/etc/slurm
      - ./shared:/shared
    hostname: slurm_controller
    privileged: true

  slurm_node1:
    depends_on:
      slurm_head:
        condition: service_started
    image: slurm_node
    container_name: slurm_node1
    networks:
      - slurm-network
    volumes:
      - ./slurm_conf:/etc/slurm
      - ./shared:/shared
    hostname: slurm_node1
    privileged: true
    logging:
        driver: none

  slurm_node2:
    depends_on:
      slurm_head:
        condition: service_started
    image: slurm_node
    container_name: slurm_node2
    networks:
      - slurm-network
    volumes:
      - ./slurm_conf:/etc/slurm
      - ./shared:/shared
    hostname: slurm_node2
    privileged: true
    logging:
        driver: none

  slurm_node3:
    depends_on:
      slurm_head:
        condition: service_started
    image: slurm_node
    container_name: slurm_node3
    networks:
      - slurm-network
    volumes:
      - ./slurm_conf:/etc/slurm
      - ./shared:/shared
    hostname: slurm_node3
    privileged: true
    logging:
        driver: none

  slurm_node4:
    depends_on:
      slurm_head:
        condition: service_started
    image: slurm_node
    container_name: slurm_node4
    networks:
      - slurm-network
    volumes:
      - ./slurm_conf:/etc/slurm
      - ./shared:/shared
    hostname: slurm_node4
    privileged: true
    logging:
        driver: none

networks:
  slurm-network:
    driver: bridge